### ISSUE TITLE
Path settings

### ISSUE THREAD

**Issue by carlca** [brettbuddin/shaden#1]
macOS 10.13.1 High Sierra
Golang 1.9.2

Hello, what path settings do I need? PortMidi was already installed so I installed PortAudio using Homebrew.

I then ran `go get -u buddin.us/shaden` whereupon I got this message:
`# pkg-config --cflags portaudio-2.0
pkg-config: exec: "pkg-config": executable file not found in $PATH`

I then ran `shaden -repl` and received this:
`zsh: command not found: shaden`

What am I missing? 
Thanks,
Carl

**Comment by brettbuddin** [comment]
You'll need to install `pkg-config` via Homebrew as well I think. Give this a go `brew install pkg-config` and then try again.

**Comment by carlca** [comment]
Hi Brett, thanks that improves matters greatly. Now when I run `shaden -repl` I get:
`PID: 34450
Seed: 1510698937904916000
Input Device: Built-in Line Input (10ms/14.081632ms)
Output Device: Built-in Digital Input (10ms/100ms)
engine error: Invalid number of channels`

Just the last line looks a bit off.

**Comment by brettbuddin** [comment]
Ah fun! Looks like I need to remove the default behavior of output selection 😄 . Could you run `shaden -device-list` and show me what you have there? That command will list all the devices (audio/midi) on your machine. We'll be choosing another index from that list and instructing Shaden to use that one instead of the default with `shaden -device-out=<INDEX>`

**Comment by carlca** [comment]
` carlca  ~  shaden -device-list                                                                                                   ✓  23:27:05 - 14.11.2017
Audio Devices
0: Built-in Line Input
1: Built-in Digital Input
2: Built-in Output
3: Built-in Line Output
4: Built-in Digital Output
5: Scarlett 2i2 USB
6: Boom2Device
7: Pro Tools Aggregate I/O

MIDI Devices
0: Oxygen 25 (input)
1: Oxygen 25 (output)`

**Comment by brettbuddin** [comment]
I'll work on decorating this output with a bit more information 😄 . For now could you give this a try: `shaden -device-out=2 examples/gates.lisp`. That references index 2 ("Built-in Output").

**Comment by carlca** [comment]
```
shaden -device-out=2 examples/gates.lisp                                                                          146 ↵  23:30:26 - 14.11.2017
PID: 37225
Seed: 1510702259922418000
Input Device: Built-in Line Input (10ms/14.081632ms)
Output Device: Built-in Output (4.648526ms/14.807256ms)
listen tcp :5000: bind: address already in use

```

**Comment by carlca** [comment]
I didn't hear anything...

**Comment by carlca** [comment]
Let me just restart iTerm2...

**Comment by brettbuddin** [comment]
I completely forgot to ask: Are you currently sitting in `$GOPATH/src/buddin.us/shaden` directory? Otherwise the `examples/gates.lisp` won't be found.

**Comment by carlca** [comment]
I sussed the directory out. Cool! I ran it with my Scarlett 2i2 USB Audio adapter as the chosen device and it sounds really good. Thanks for this!

One question before I play around with this. Once I start a `shaden` command, what's the recommended way to cancel it so that I can put in a new command?

**Comment by brettbuddin** [comment]
I just posted a video as an overview of how I use it. 

https://www.youtube.com/watch?v=GbUTo6sPnW8

I would suggest either using my method (which only supports Vim currently) or the `-repl` flag to enter the REPL. Otherwise you'll need to kill the process in order to reload it.

**Comment by carlca** [comment]
Cool. I'll czech that out. It's getting late here in London, England so I'll bid you good night, and thanks again! Cheers, Carl.

**Comment by 1l0** [comment]
> ```listen tcp :5000: bind: address already in use```

Same on macOS. Just add another port instead of default to get working.
```
shaden -addr ":8080" gates.lisp 
```
