### ISSUE TITLE
midi-input receives zero value

### ISSUE THREAD

**Issue by semrekkers** [brettbuddin/shaden#2]
Hi!

First of all, love this brilliant piece of software! However, I can't get `midi-input` get to work. This is an example of how I use it now:

```lisp
(define midi (unit/midi-input (table :device 3 :channels (list 2))))
; ...
(-> oscillator (table :freq (<- midi "2/pitch")))
```

Maybe I'm using it the wrong way, but `(<- midi ...)` always returns a zero value. Shaden receives my MIDI events and also sends them through the `eventChan` (midi.go:74). Functions `IsProcessable()` and `ProcessSample(i int)` with receiver `pitch` or `cc` are never called, but `Out()` is called frequently. At least, on my machine.

Can you or somebody give me an example how to use it properly?

OS: `Ubuntu 17.10`
Go: `go version go1.9.2 linux/amd64`
Shaden: `188875d27498460cbc8c6285c96cef3c3c69effd` (latest at this time)

Thanks,
Sem

**Comment by brettbuddin** [comment]
Sounds like a bug. I'll take a look 😄 . Stand by...

**Comment by brettbuddin** [comment]
Found the bug. Will issue a fix and let you know when its up.

**Comment by brettbuddin** [comment]
Could you pull lastest `master` with `go get -u buddin.us/shaden` and try again? It's not currently documented, but I have implemented a [`unit/debug` Unit](https://github.com/brettbuddin/shaden/blob/master/unit/debug.go) that is pretty useful in situations like this for inspecting outputs. Here's a quick example of its usage:

```lisp
(define controller (unit/midi-input (table :device 1)))
(define debug (unit/debug))
(-> debug (table :in (<- controller :1/cc/1)))
```

**Comment by semrekkers** [comment]
Yes, I noticed and used your `unit/debug` already :smile:. Now I see the value change correctly, thanks a lot!
